plugins:
  - jekyll-relative-links
relative_links:
  enabled: false
  collections: false
include:
  - README.md
  - LICENSE.md
title: Co-Cooking with Care
markdown: GFM
show_downloads: false
theme:  jekyll-theme-architect
