plugins:
  - jekyll-relative-links
  
relative_links:
  enabled: true
  collections: false
  
include:
  - README.md
  - LICENSE.md

markdown: GFM
show_downloads: false
theme:  jekyll-theme-architect
title: Co-Cooking with Care
